server:
  port: 9999

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/nanjo/spring-cloud-config.git
          username: nanjolono
          password: password
