server:
  port: 9001

spring:
  application:
    name: authorization
  redis:
    database: 0
    host: 10.211.55.6
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
  cloud:
    nacos:
      discovery:
        server-addr: 10.211.55.6:8848
nacos:
  discovery:
    server-addr: 10.211.55.6:8848
    auto-register: true
    register:
      service-name: authorization
      group-name: public
      ip: 192.168.1.53
      port: 9001
    namespace: public