server:
  port: 8083

spring:
  application:
    name: nanjolono-provider-8081
  #配置jpa
  jpa:
    # 指定是否在spring容器启动时创建表，默认位false
    generate-ddl: true
    # 指定是否在控制台显示sql
    show-sql: true
    # 指定应用重启时不重更新表
    hibernate:
      ddl-auto: none

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///test03?useUnicode=true;characterEncoding=UTF-8
    username: root
    password: z9426464
logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    org.hibernage: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.nanjolono: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: nanjolono-provider-8083
info:
  auth: Tom
  app.name: provider8081
  app.desc: this is a provider
  company.name: www.nanjolono.com
  company.addr: chian zhejiang