server:
  port: 9999

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/nanjo/spring-cloud-config-server.git
          username: nanjolono@outlook.com
          password: z9426464
