spring:
  application:
    name: nanjolono-consumer-depart
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: nanjolono-consumer-8080
ribbon:
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
